### ISSUE TITLE
Minify feature

### ISSUE THREAD

**Issue by alimbada** [DAXaholic/vscode-edifact#21]
Hi there,

Any chance you could add a "minify" feature?

Basically, it should be the opposite of the format command so rather than separating the segments on to individual lines it should bring them all back onto one line.

Currently what I'm doing is selecting all the lines (segments) and then using the built in VS Code command "Join Lines" to bring everything back to one line but then having to replace all spaces except the first space in the first segment(`UNA:+.? '`) but it gets quite tedious.

Thanks,

Ammaar

**Comment by DAXaholic** [comment]
Yes I think this shouldn't be a big deal to develop. Thanks for the idea!

**Comment by DAXaholic** [comment]
Version 0.7.0 is out with a new command to put all segments in a single line. Let me know how this works out for you.

**Comment by alimbada** [comment]
Works great. Thanks for the quick update!
